spring:
  application:
    name: product-service

  cloud:
    gcp:
      project-id: mspr2-460513
      credentials:
        location: file:/E:/EPSI/MSPR2/secrets/mspr2-broker-secret.json

  datasource:
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework.security: debug
