name: Release on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Tag and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Bump version and create tag
        id: versioning
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          RELEASE_BRANCHES: main
          DRY_RUN: false

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.versioning.outputs.new_tag }}
          name: "Release ${{ steps.versioning.outputs.new_tag }}"
          body: |
            🎉 Release automatique générée par GitHub Actions.
            ✅ Version : `${{ steps.versioning.outputs.new_tag }}`

        env:
          GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
